replicaCount: 1

image:
  repository: 2024aa05086/heart-disease-api
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  name: heart-disease-service
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30007

nameOverride: ""
fullnameOverride: ""
